name: Create GitHub Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if:  startsWith(github.head_ref, 'release/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Project (if present)
        run: npm run build --if-present

      - name: Get version
        id: get-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          draft: true
          tag_name: v${{ steps.get-version.outputs.version }}
          generate_release_notes: true
          files: dist/*.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
