name: Publish Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'release')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Build Project (if present)
        run: npm run build --if-present

      - name: Get version
        id: get-version
        run: echo ::set-output name=version::$(node -p "require('./package.json').version")

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: v${{ steps.get-version.outputs.version }}
          generate_release_notes: true
          files: dist/*.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
