name: Release
on:
  workflow_dispatch:
    inputs:
      draftRelease:
        description: 'Draft release'
        required: true
        default: true
        type: boolean
      dryRun:
        description: 'Dry run'
        required: false
        default: false
        type: boolean
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint --if-present
      - name: Run tests (if present)
        run: npm test --if-present
      - name: Build Project
        run: npm run build --if-present
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.js
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: ${{ github.event.inputs.dryRun }}
          semantic_config: |
            {
              "branches": ["main"],
              "plugins": [
                ["@semantic-release/commit-analyzer", {"preset": "angular"}],
                ["@semantic-release/release-notes-generator", {"preset": "angular"}],
                ["@semantic-release/github", {"draft": ${{ github.event.inputs.draftRelease }} }]
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Echo New Version
        run: echo 'Publishing version ${{ steps.semantic.outputs.new_release_published }}'
      - name: Download artefacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"
      - name: Upload assets to release
        run: |
          VERSION=$(echo ${{ steps.semantic.outputs.new_release_published }} | sed 's/^v//')
          gh release upload "v$VERSION" dist/*
