name: Release
on:
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'Version Increment Type'
        type: choice
        required: true
        options: ['patch', 'minor', 'major']
        default: 'patch'
      draft:
        description: 'Release as Draft'
        type: boolean
        required: false
        default: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Run linter (if present)
        run: npm run lint --if-present

      - name: Run tests (if present)
        run: npm test --if-present

      - name: Bump version and generate changelog
        id: bumb-version
        uses: phips28/gh-action-bump-version@v10.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          version-type: ${{ github.event.inputs.version_increment }}

      - name: Build Project (if present)
        run: npm run build --if-present

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: ${{ github.event.inputs.draft }}
          tag_name: ${{ steps.bumb-version.outputs.newVersion }}
          generate_release_notes: true
          files: dist/*.js
