name: Release
on:
  workflow_dispatch:
    inputs:
      draftRelease:
        description: 'Draft release'
        required: true
        default: true
        type: boolean
      dryRun:
        description: 'Dry run'
        required: false
        default: false
        type: boolean
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Run tests (if present)
        run: npm test --if-present
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: ${{ github.event.inputs.dryRun }}
          semantic_config: |
            {
              "branches": ["main"],
              "plugins": [
                ["@semantic-release/commit-analyzer", {"preset": "angular"}],
                ["@semantic-release/release-notes-generator", {"preset": "angular"}],
                ["@semantic-release/github", {"draft": ${{ github.event.inputs.draftRelease }} }]
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo New Version
        run: echo 'Publishing version ${{ steps.semantic.outputs.new_release_published }}'
